version: "3.8"

services:
    postgresql:
        image: postgres:14.4
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: sqlhaslo
            POSTGRES_USER: postgres
            POSTGRES_DB: sqlbaza
    
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: sqlhaslo